---
site_name: MkDocs Zettelkasten
site_description: Theme and plugin to implement Zettelkasten in MkDocs
site_author: Tomáš Bouška
site_url: https://buvis.github.io/mkdocs-zettelkasten/

repo_name: buvis/mkdocs-zettelkasten
repo_url: https://github.com/buvis/mkdocs-zettelkasten
edit_uri: "edit/main/docs/"

copyright: Copyright &copy; 2021 Tomáš Bouška

theme:
  name: zettelkasten-solarized-light
plugins:
- search
- tags
- zettelkasten

markdown_extensions:
- admonition
- meta
- codehilite:
- pymdownx.superfences

nav:
- Install: 20211122194827.md
- Run a demo: 20211122195311.md
- Requirements: 20211122195910.md
- Features: features/index.md
